/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'lopidio' at '3/17/17 10:44 PM' with Gradle 2.14.1
 *
 * @author lopidio, @date 3/17/17 10:44 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
